apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-gluetun-secret
  namespace: jellyfin
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgCfsQ5jjdwFYw6vm3pfMDsnQ4K9qBJLkfFL83p+vvlr0IekK65bWnFdOMPejHi3KF5057mk02kq1VuDioSP3FpvkMCYLrOaBhkCzEFN5R974I/TzkFqhN60hPfX2lnC5nRZxelPbpuaaVyvDpCUi1EcTC75ddlUg5SERN024hGmm1dMssf6YJlyOg070o/KhSUHLOy1ky6XI5tYDeflyf4xVYXb/p2qhhE+1nDfVqU6M8ZAv2aOZ+qf6jQ3Dmojvw4OYC6UTh611YeisTJ7cuJhza5j2Vo9s9zr5htaSxuHGz+8G1+Z10gPXtFjUmJMYrMIqDu+mfSmC4uMaHjC48BZmOz0RLD7bMfkU185CSp3lOUztzkgEu8p2HlZ/Y2E2y+kcmUwt1S1GliJaf9xNhGEFOnpDf6ZMv5g2pw9oUpCiVEuFgAItobN6KlkTbyreCHQyL7TSkQqKAwxGEululi4XqLdZjZN3WGCD0BV8XQ6YnPtNImJkGO1XeSui7flnlKerXY+j6xbpRyoM6ClF6FPwxF/7ncCwPbr9lNT9ZZkQUtQRv/taJ+Kuj/yXF1fVU7VGcao49V534ifZ902ux/VgHhIuz0tIiaJlRutxIrNGOhGla6ngpFqL40CJNDBEcU0tau5hajjtAbTAyuK2MlH00Y1LWgI9iWnij4v1ZSvffRgMUSZqd0by+A1iZU79HP9ZvUTl6vhds+GtEK38LYr5rYqYykgpVsdO+20tNflvPoWQ9wXpSV4FA25cw==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-gluetun-secret
      namespace: jellyfin
    type: Opaque

