apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: opencloud
spec:
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - name: tika
        image: apache/tika:3.3.0.0
        ports:
        - name: http
          containerPort: 9998
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
