apiVersion: kustomize.axolotl.cloud/v1alpha1
kind: JsonnetGenerator
metadata:
  name: kube-prometheus-generator
  annotations:
    config.kubernetes.io/local-config: "true"
    config.kubernetes.io/function: |
      container:
        image: kustomize-generator-jsonnet:latest
        mounts:
          - src: ./jsonnet
            dst: /jsonnet
            type: bind
            rw: true
        network: true
spec:
  projectDir: /jsonnet
  projectFile: config.jsonnet
  useJsonnetBundler: true
