apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC9DVRYa0lKH0oGawvu0eryJ9Arc0NphVUKqU+m8Lz4MIzKNfWJipRIHX3yhp9oeicC/rtBulcvCBBx+Ko9QinW+EodWuYEaCy8IXzF5HSSp7YOTQ7FvXVfPvVGex6UlJ7g0Z2NXjsGDo0VPuJOwzG0fKmyBPetTrWRfphq6rGqgusgHablsGyjYnwhM289gMU0LbeAh5qIFXj37qtVLJ+QdELRPJvOsSaasPx2jbOeaA95WedgukauO9CdpQGQcQUSX+pY6yJWXdIiajOoA6FRKJpyBBMOOq3xyRBJlVE1Pf4IgLCyqabOvJr2tDAi4z6RSNwjYIuq3TASpdN6srxxJTCopyuPr/iciSYr9r6f5yo8J2AFoQMI1cMPBCkap9VD8q7BYlw6ZK8RaTYqwj4+Vv1kd2rengAsHKO2mh9rytMfvIoiuQ0B2HFGpqLUnZLA0x1eYjsq5MnhP6FaYKEykOPjY0aWwQ7TTMja2jxO3UgEWdjrQ9DfncqzX7HtXpCNZbsxmKC0hgcuGGnyDVaXX/nNQs8QvcYllrqr8hkcLrdSmI4IMe9C4cDj7R6zeGjITUaa4QSKWLGK4ZeOOEnr/GRnMyP8JHDekfmJtKaX90ZCuVuXBDroiaWDxF8/zmGPfP6GcRX4Rhxtdp19K14KxjGsWNPZakcZybKG5B/FCM2BngHILpleycbo8S7fxmTuO7xVYXZFoq5bqtrupbBtupSNBTB61qoe4HokyQ64Ej9T2ZeGYb/4
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque

