apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencloud
  namespace: opencloud
spec:
  selector:
    matchLabels:
      app: opencloud
  template:
    metadata:
      labels:
        app: opencloud
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: opencloud
        image: opencloudeu/opencloud-rolling:6.1.0
        command:
        - /bin/sh
        args:
        - -c
        - opencloud server
        envFrom:
        - configMapRef:
            name: opencloud-config
        - configMapRef:
            name: opencloud-oauth2-config
        - configMapRef:
            name: opencloud-s3-config
        - secretRef:
            name: opencloud-s3-secret
        - secretRef:
            name: opencloud-smtp-secret
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
        ports:
        - name: http
          containerPort: 9200
        - name: microregistry
          containerPort: 9233
        volumeMounts:
        - name: opencloud-config
          mountPath: /etc/opencloud/opencloud.yaml
          subPath: opencloud.yaml
          readOnly: true
        - name: opencloud-app-registry
          mountPath: /etc/opencloud/app-registry.yaml
          subPath: app-registry.yaml
          readOnly: true
        - name: opencloud-csp
          mountPath: /etc/opencloud/csp.yaml
          subPath: csp.yaml
          readOnly: true
        - name: opencloud-banned-password-list
          mountPath: /etc/opencloud/banned-password-list.txt
          subPath: banned-password-list.txt
          readOnly: true
        - name: opencloud-data
          mountPath: /var/lib/opencloud
      volumes:
      - name: opencloud-config
        secret:
          secretName: opencloud-config-secret
      - name: opencloud-app-registry
        configMap:
          name: opencloud-config-files
          items:
          - key: app-registry.yaml
            path: app-registry.yaml
      - name: opencloud-csp
        configMap:
          name: opencloud-config-files
          items:
          - key: csp.yaml
            path: csp.yaml
      - name: opencloud-banned-password-list
        configMap:
          name: opencloud-config-files
          items:
          - key: banned-password-list.txt
            path: banned-password-list.txt
      - name: opencloud-data
        persistentVolumeClaim:
          claimName: opencloud-data
