apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./configmap.yaml
- ./deployment.yaml
- ./httproute.yaml
- ./objectbucketclaim.yaml
- ./objectstoreuser.yaml
- ./opencloud-config.sealedsecret.yaml
- ./pvc.yaml
- ./s3.externalsecret.yaml
- ./secretstore.role.yaml
- ./secretstore.rolebinding.yaml
- ./secretstore.serviceaccount.yaml
- ./secretstore.yaml
- ./service.yaml
- ./smtp.sealedsecret.yaml

configMapGenerator:
- name: opencloud-config-files
  namespace: opencloud
  files:
  - files/app-registry.yaml
  - files/csp.yaml
  - files/banned-password-list.txt
