apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-data
  namespace: opencloud
spec:
  storageClassName: rook-ceph-fs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi # Needs to be large as it is temporary storage before files are uploaded to S3
