apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud-s3-secret
  namespace: opencloud
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: opencloud-s3-secret
    template:
      data:
        STORAGE_USERS_DECOMPOSEDS3_ENDPOINT: "{{ .endpoint }}"
        STORAGE_USERS_DECOMPOSEDS3_ACCESS_KEY: "{{ .accessKey }}"
        STORAGE_USERS_DECOMPOSEDS3_SECRET_KEY: "{{ .secretKey }}"
  data:
  - secretKey: endpoint
    remoteRef:
      key: rook-ceph-object-user-axolotl-private-object-store-axolotl-opencloud
      property: Endpoint
  - secretKey: accessKey
    remoteRef:
      key: rook-ceph-object-user-axolotl-private-object-store-axolotl-opencloud
      property: AccessKey
  - secretKey: secretKey
    remoteRef:
      key: rook-ceph-object-user-axolotl-private-object-store-axolotl-opencloud
      property: SecretKey
