apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opencloud-smtp-secret
  namespace: opencloud
spec:
  encryptedData:
    NOTIFICATIONS_SMTP_PASSWORD: AgC+kbhqlN1U0ITtaGuzjLoQjFCq3T6yaQE5U0yZVeHYWTQnn+89lS/GGpUsvaNpzsQsfBc9Px0yrKPXpduLXa7r1HpVA91LZxZDVb+ZfoEzk1B4oObvNoRUqtdzalkT8Vx1xsvhi1SytC73ut1+89Mb8eosj03TwSxdKOguP5a8Qr1TJcFm3VyURbbsKWcreYIZY2ECoR5KvPhFzCpLVzsJ8iPW+76l1+7qfpHAwlw5hQUf6GYdvtgbGNlDKNKHvAQrooPSOaEEXmLqJBOhBmB9+XaYe7rkfu5B6EAscVepTDHcz4Td8tUY+wwkZKX1jBKfSRSpYbdrBdYLPB/N9oKe6m2A5RANBTSd97D6XNYo3iwg5vI+2+Hb/b+OXtEtE0UW82aVj46FJBSMTtgvIABHfjRkxRWeo/MEHu/1aCHPhl2YgU24EtjIZ7D3Uqn4gYUQP+gHwHfR7bXxSCEPNURMBzmr1nI5c9gdCDCkNorqVBPFS7sieMYMYTriSsP/mwdYHS+W2ARN4O2BsxiRpFshIyUoQ9dQucSZt0as1+kaW5J90gNOMlaW5m0plNswUUZg0jFiuo6GgRvMEmSI8m3ay4WDBE5mgmRXSWzTlAqgazBSV9CtgFouFnzNYIvabN49lCzdKGsswZYPte18bgWcCkDCW4K33ULFiZDBDwTC4gLH51DlbKrLBuKeLpE0U9F7c5M/zD/zFT+UPJVPwGwS
  template:
    metadata:
      creationTimestamp: null
      name: opencloud-smtp-secret
      namespace: opencloud
    type: Opaque

