apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: default
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
  - name: axolotl
    localASN: 64513
    peers:
    - name: router
      peerASN: 64512
      peerAddress: 10.0.10.1
      peerConfigRef:
        name: default
