apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./bgpadvertisement.yaml
- ./bgpclusterconfig.yaml
- ./bgppeerconfig.yaml
- ./gateway.yaml
- ./ippool.yaml

helmCharts:
- name: cilium
  namespace: kube-system
  releaseName: cilium
  repo: https://helm.cilium.io
  valuesFile: values.yaml
  version: 1.18.0
  includeCRDs: true
