apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/rook/rook/v1.17.7/deploy/examples/common.yaml
- https://raw.githubusercontent.com/rook/rook/v1.17.7/deploy/examples/crds.yaml
- https://raw.githubusercontent.com/rook/rook/v1.17.7/deploy/examples/operator.yaml
- https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v8.3.0
- https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=v8.3.0
- ./blockpool.yaml
- ./cluster.yaml
- ./dashboard.httproute.yaml
- ./filesystem.yaml
- ./groupsnapshotclass-fs.yaml
- ./objectstore.yaml
- ./rgw.httproute.yaml
- ./snapshotclass-fs.yaml
- ./snapshotclass-rbd.yaml
- ./storageclass-bucket.yaml
- ./storageclass-fs.yaml
- ./storageclass-rbd.yaml

patches:
- path: ./operator.configmap.yaml
- target:
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: Replace=true
- target:
    kind: Namespace
  patch: |-
    - op: add
      path: /metadata/labels
      value:
        istio.io/dataplane-mode: ambient
        pod-security.kubernetes.io/enforce: privileged
