apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: grafana-operator
  name: grafana-operator
  namespace: grafana
spec:
  endpoints:
  - path: /metrics
    port: metrics
    interval: 60s
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-operator
