apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: grafana-operator
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
  - path: /metrics
    port: metrics
    interval: 60s
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-operator
