apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./grafanadatasource.yaml
- ./namespace.yaml
- ./objectbucketclaim.yaml

helmCharts:
- name: loki
  namespace: loki
  releaseName: loki
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 6.35.0
