apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: immich
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.2.0
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
