directives:
  child-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  connect-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  - 'blob:'
  # - 'https://${COMPANION_DOMAIN|companion.opencloud.test}${TRAEFIK_PORT_HTTPS}/'
  # - 'wss://${COMPANION_DOMAIN|companion.opencloud.test}${TRAEFIK_PORT_HTTPS}/'
  - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
  - 'https://login.microsoftonline.com/'
  - 'https://update.opencloud.eu/'
  default-src:
  - '''none'''
  - 'https://office.axolotl.cloud/'
  font-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  frame-ancestors:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  frame-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  - 'blob:'
  - 'https://embed.diagrams.net/'
  # In contrary to bash and docker the default is given after the | character
  # - 'https://${COLLABORA_DOMAIN|collabora.opencloud.test}${TRAEFIK_PORT_HTTPS}/'
  # This is needed for the external-sites web extension when embedding sites
  - 'https://docs.opencloud.eu'
  img-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  - 'data:'
  - 'blob:'
  - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
  - 'https://tile.openstreetmap.org/'
  # In contrary to bash and docker the default is given after the | character
  # - 'https://${COLLABORA_DOMAIN|collabora.opencloud.test}${TRAEFIK_PORT_HTTPS}/'
  manifest-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  media-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  object-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  - 'blob:'
  script-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  - '''unsafe-inline'''
  - 'https://login.microsoftonline.com/'
  style-src:
  - '''self'''
  - 'https://office.axolotl.cloud/'
  - '''unsafe-inline'''
