apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gate-secret
  namespace: minecraft
spec:
  encryptedData:
    CONNECT_TOKEN: AgDAa5JDxzLHzLmoyJv63jeJVgWaXLqv/7lxO3TZi+xg73KH+OwQChuzlTzrPYF2MXlSspiNMTYan7wZNfKgqxLMbrGQDNiI46lknEFf490A030i8Kre+vRjyilBkqrZ5hSuOma6o8x8F0CpSM5aCnzuFzqT9AsZVT6OahcOQ9fO0uFj4r8ptWVkfKNAywRgmEQoE4nsZo8dc341Pb/kXlThFtOjt+ykHuh9RYuDoe0vTeumhvjwsssRRcb/Ayoa0zcDPtcCQFQoi4D2pdX/NP00P06PA6cQEln12Cxqc7CzYi5WdToU8WgzLbs672JQT+SW939SVGTsUM+pPo94vWQCLNv+EJEvAeMJgYemqM0m9kZNbRAsVD+KiRf5zl6h4IW2rVVcLCYPkyP/WhcANtb2MZPXNktSD2gClhItEvuAEBWTOHATDnnXX8E6wttA47M1W9elgaqzRPpT4CMGUtISrfKBydsD+zUy+8IZgzU2RZ1gvmO505BZLlXlly9QmIb/nS+j6qoM66wxWK2/MtS5LF3mS9kPuX91FjYniA6KI3dw/sZsQhYCidZnelUugmOf8cYQlclhkIYfbfFcQ6GcZO/gdtmGxf9s2p59XdCHeZ/7lMXgB0S6njeKD5euI6j+sV+h782IhJMcVrHHgpWAGeOI9JCoiZ+Pb44NmWBr1krMtsJMzmAycQ2q7VFPEwCDcueSR9cpdahMXQVCqcUxEjEyma4kzjk=
  template:
    metadata:
      creationTimestamp: null
      name: gate-secret
      namespace: minecraft
    type: Opaque

