apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml

helmCharts:
- releaseName: redis-operator
  namespace: redis-operator
  name: redis-operator
  repo: https://ot-container-kit.github.io/helm-charts
  version: 0.21.2
  valuesFile: values.yaml
  includeCRDs: true
