apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./azuread.provider.yaml
- ./azuread.providerconfig.yaml
- ./azuread.runtimeconfig.yaml
- ./azuread.sealedsecret.yaml
- ./namespace.yaml

helmCharts:
- name: crossplane
  namespace: crossplane-system
  releaseName: crossplane
  repo: https://charts.crossplane.io/stable
  valuesFile: values.yaml
  version: 1.20.0
  includeCRDs: true
