apiVersion: v1
kind: Service
metadata:
  name: minecraft-vanilla
  namespace: minecraft
spec:
  clusterIP: None
  selector:
    app: minecraft-vanilla
  ports:
  - name: tcp
    port: 25565
    targetPort: tcp
    protocol: TCP
  type: ClusterIP
