---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-secret
  namespace: grafana
spec:
  encryptedData:
    webhookUrl: AgBuU/xJfcdMoKpNiTfLXpXm2EXzu2GkqaWu7WMVN68uC0OrfYLdGxd/uDVlooVNBk/LUHUM9vW8ABC/xu8td0mrvz01l1qji0/LNCI1+uiotkRuN6RbI1k5dfDGlXBWPbY5uJ6LyVC5TYOpO0qypMA5MEh6qpRYWqJRvkrWH/CQOBwcWgcGfqa2amwi2pf7VI6+W5oriGct7Sr4o4dy/FO//cDpPeBsM9t/FxuXQOuMTqz1UoRRuuXjy0+cFfVpKlyNW5vH2QoJt5dyc6U6r2Xsc0ZP3nOWLOCXgAl9Bv1QN1UbiO8bzxtbe9JD0S0Ea675IGMPlCDmX75b3giZ9IVDkfnSEaPSRwgVQzToYMAOUJnlP7b41JPGqqc6V8OyerJp23VitDMGOW4Xx/zpNk8HLGqKokxn/JWPb0KLIv2oHjc2qq77ytGpF056Xv0pONWNKsDXLYg1jK8qxY40eNI8DsPOe1SheCKe5Ps2Wmnk4AmARZG6NW0pI4wyuimjJ/ohZ5w8jeRayMubO2ghH/KkgozxWrA8t/VrLpvNkw/X3jKh4KFwflJRfGonc0LXmSoH6g9QgymRXdQBtZKg1Xlbvytln7Rfw6wMunNDFWQA2d1BqI1/YaLMyCBzmo9+PLCH9NHqXziXnJLed6Z5RhRbcVC9Awn8hT4ysaHSQpy0Z7CFPZhf1oW+AcT+PRutTGxjVpfUR1WCm0rv8Uc2uDlMvc2fYs87nkSLgU2wf1OwrFrasEaELrWTC/xlCMSbJb0QJ084hbM7G2j2CBbqCIlbj0xEP5vlH7xtdRj5WbvS6If6lUNBB4OiG5HgvW1qxDSB6j79iuBVFcNRwh012qzxIiNdlf4Zghg=
  template:
    metadata:
      name: discord-secret
      namespace: grafana
    type: Opaque
