---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-secret
  namespace: default
spec:
  encryptedData:
    webhookUrl: AgAkG77WhHZ0EEp6bh1x+v6E8ms1y8EPYTUaV4y3JgJTNFjRNwZlvxbA3c0dSxpdkyMZ6S/jc8HYlyrdYGznPNZzWDMKqu07MXCScoVfI9k1DHi0Ga8tVv0m+JHIfluAo2c19+PMz7EvaFBqQOQOh8WXi67H73pU5010nlcW6mDS4Kpv3htR6GRut4ynj1iJh6gPNvfVZpO33wdgOhyGUEz8YxYx5FYnlFCowPk4rQzV4E4kR9nSPVZ1t6SfpoHenqQTiOuodT8yoGCm4esrHNOXZjUqogskfmtEKOt7qjlZ0N2oGokojrOojYTvz7/6PrgjNg4InlBy/InpoQHLMeTDEIeaXTf/P0jpj1KzYTqxxxLKbtzL/Hp4moWRfgZb9RBxg2SSF/r78z1Mq8uXCtJosrgrhRFA+gsYScMcDYxpY2kGWX79hTHyL2OfdaiPsNIY7bHZjuwB6Cw+NyLOY2SklT/Tu1MVXCYOqLJF/KuwRS0JnTRwXwOIAKrG/I83XHdvmDdZI2C2YhH+klAVXioSnIBnPjelgsmxOFaHvg3yt0lLyUZN4zYCoqhJSWOHjx59d9ElGPa3IL5lGavlNgwJ43atv+g77A4BGcqf0n3isQ3BoaF9GEorT7wOvBV51Sy/xqOlmtrBkNBH3/sBhavlpuKVcdpxm5f+51R/YdHzxdeJCIwNpy8y5AvAGtaW0gVvDCaz8zKiLvHFIHORJ3qM4cCOY7SY7TmXEMWhAFIHTHPANA/QeV2nepMmBHaBWUOY4ReNY5Re/qsRb1Egl1CokFQNvxULj8Ojo2dozInphNWUQAqB/jDn/DrdTA57PZ3glv9+zbNf/2HFtWWzdIbCcEVje7kgXNs=
  template:
    metadata:
      name: discord-secret
      namespace: default
    type: Opaque
