apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: grafana
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: grafana
            env:
            - name: GF_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: host
            - name: GF_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
            - name: GF_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: user
            - name: GF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: GF_AUTH_AZUREAD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana-client-secret
                  key: attribute.value
            - name: GF_AUTH_AZUREAD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: grafana-client
                  key: clientId
            - name: GF_AUTH_AZUREAD_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-client
                  key: authUrl
            - name: GF_AUTH_AZUREAD_TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-client
                  key: tokenUrl
  config:
    server:
      domain: grafana.axolotl.cloud
      root_url: https://grafana.axolotl.cloud
    log:
      mode: console
    database:
      type: postgres
    security:
      cookie_secure: "true"
    auth:
      disable_login_form: "true"
    auth.azuread:
      name: Microsoft
      enabled: "true"
      allow_sign_up: "true"
      scopes: openid email profile
      role_attribute_strict: "false"
      allow_assign_grafana_admin: "true"
