apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./dashboards
- ./entra
- ./discord.grafanacontactpoint.yaml
- ./discord.sealedsecret.yaml
- ./grafana.yaml
- ./httproute.yaml
- ./postgres.yaml
