apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: collabora-secret
  namespace: opencloud
spec:
  encryptedData:
    password: AgDDRMOBD6W5SUsbClvmZzzwoReSXNd2/iZlnSuzVnWaYqlDwDlpPsuVDLoTop6SW+71j32jQs+plnnuLPGtX/D52NfxzzFePOtH9KOG/mnK3dSH8Pp21V7bRhe+j3n4zXpgHK8xdKeK18S7w7G/eqMthWeyyqApGvy5W2+tJWZco9GUmcr8xy5MjeXUdb+GGpCvQzyU4FZcrgTgnNENfN/vStTDnMSC5IogJqngziaTCLvwOC6T0KWbS3SYc2Wkuq5cZAKiaeQulOy9g+AtBs5rMxWIbseuvMJaRhix4H3Wsu09xqXi6NhqChzXNUqUZymXs4nE+31nRptEwN/+0E1s+5VzJzO8EJy/X3NzbfltioIueflUBS8hlvL9XheZrPhoevHIdM0uhQ/BxeTPjeuyLQ3ZNkj3jkFOTHgSnEsaxJbfdI7k5KKfbCdNEweegpMAsQSkFmsrqc2+Syw5XCK59yHKJ+sEvJFtKLcJq7QZDoee+ju4J303AqHPNaMDdaMLVIZOLjL3Dlt0mBSE5Zig9a9zWQCGztXWzZE2PQBQ9ZjKNQbk3jJod+zPnXg+znYhlQbRri33/1HoqId3Gx2ZJdqk53HYHfn5Mh8TkUgH6ipJN9avSKIGFtR8XgcqmB+K0KhFkPAS21dhMz2sH17ObEXfx9Zgg+8DkOBeuoalh4aFuXcC+OXUQdx6FNX7GsiodKR3BAC/+Dl5htF9GOtZrkGc1isVeH9eMdMclQ713Q==
    username: AgCiCpQA6Krc3pptOGcNGr3YPYshWYa+q2hMlmItI3QRhVqWANYX443WdvAH8L/fytgOvY6p/hiw3T/NcidFTbNjKIMxMoBQWCBDO4AHa0PA12TAD6vXNXQude/OGkPyiM8uMK5WjfCbwY4VEJh3xnNetBtoD06W2E2JTDwmxOLqOdlszNWIns4xdVm8RiMdlHB7Xsb5pU6pwEvg8S223u923+F20xrlkxU8St4pGhepVeow/O49INSqRPJFqDbcw2TK3zPOcYXnxd86falUlFAwsqpldYE6urIuS/eEH0VRQaj+3p+7niyvrgfiRpacfLSt/P+GXf88F97TwBPdmqtzAt4EtM626SXCjnPWRiDOGkROt28iQDgHL0cKOVG0uT4BIdItFZ5PU8tq1Nv4jbtOEYOqfCpRDVE31BMChF8aDXRBSIBUWiYPgFJUlcYYNDrciUQ9oC9L/AXGXfGU2ceHVa0QdcovZkHLF4i7XoVQdBIOFaAdT+R06pzV1nxNX6LnaqUst3gwPQkEMcwhCosgdpvbkh0OWOkcu5N/sna1fa4A1wlI3EWIZSfBSDhq3aQbFlhGskPz8luYutVrsiVsAEcUuX6A+0leu9aOxAAJoP8y5S5PhG965lEIUBwRVhid12i7qlhBokGZbxk4n4oDOL79FrrVc5t7ipbSqGK2aPPSlprqkw48bJQCU3QmJknEG+BAzA==
  template:
    metadata:
      creationTimestamp: null
      name: collabora-secret
      namespace: opencloud
    type: Opaque

