{
 "title": "Kubernetes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster RAM usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_Active_bytes) / sum(machine_memory_bytes)"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum (machine_cpu_cores) * 100\n"
    }
   ]
  },
  {
   "title": "Allocated pods",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{job=\"kubelet\"} / 250",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{job=\"kubelet\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network Activity - TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_network_transmit_bytes_total{device!=\"lo\"}) by (instance)",
     "legendFormat": "{{ instance }} - tx"
    }
   ]
  },
  {
   "title": "Network Activity - RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_network_receive_bytes_total{device!=\"lo\"}) by (instance)",
     "legendFormat": "{{ instance }} - rx"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "machine_cpu_cores" },
    { "expr": "machine_memory_bytes" },
    {
     "expr": "label_replace(kube_node_info, \"kubernetes_io_hostname\", \"$1\", \"node\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "CPU usage by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory usage by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (node_memory_Active_bytes / node_memory_MemTotal_bytes * 100)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "graph",
   "description": "Only contains applications we have deployed with an app label",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "description": "Only contains applications we have deployed with an app label",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container!=\"\"}[1m]) * 1000) by (pod)\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU usage per node and type",
   "type": "graph",
   "description": "Only contains applications we have deployed with an app label",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (mode, kubernetes_node) (irate(node_cpu_seconds_total{job=\"node-exporter\"}[5m]))",
     "legendFormat": "{{kubernetes_node}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Pod CPU throttling",
   "type": "graph",
   "description": "Ideal is minimum",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\".+\", container_name!=\"POD\", image!=\"\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Prometheus status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job!=\"kubernetes-pods\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}