apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:opencloud-application-reader
rules:
- apiGroups:
  - applications.azuread.upbound.io
  resources:
  - applications
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:opencloud-application-reader
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno:opencloud-application-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno:opencloud-configmap-writer
  namespace: opencloud
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno:opencloud-configmap-writer
  namespace: opencloud
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
roleRef:
  kind: Role
  name: kyverno:opencloud-configmap-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno:opencloud-configmap-reader
  namespace: opencloud
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno:opencloud-configmap-reader
  namespace: opencloud
subjects:
- kind: ServiceAccount
  name: kyverno-admission-controller
  namespace: kyverno
roleRef:
  kind: Role
  name: kyverno:opencloud-configmap-reader
  apiGroup: rbac.authorization.k8s.io
