apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./chart
- ./entra
- ./httproute.yaml
- ./namespace.yaml
- ./postgres.yaml
- ./redis.externalsecret.yaml
- ./redis.sealedsecret.yaml
- ./redis.yaml
- ./sealedsecret.yaml
- ./secretstore.role.yaml
- ./secretstore.rolebinding.yaml
- ./secretstore.serviceaccount.yaml
- ./secretstore.yaml
