---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: sure
spec:
  encryptedData:
    password: AgCZkUnmKZxWaPg/myg9JyGpuWKFcY1FyA+FFoYNe+Obk/VLICisMe/H/beuc0heNzwbvTIdF+xfYOpKdA195Hgvk4xzBwkgg6IgH5ayqnz09gl8HAcRxRZzIaUHWahpoe8kenGlPVFk/0U3Pa8pxA/lJvp84Ew8G3dS/GCvs+cZ/e3Tb9lKP1XkW4Mk3m1N/eCyITxp1++ZcZ8jQz+wXJr2GHFs8l6b3LhJiuzZBl3adqnYqWbBgWgme94oVgf7X4+SAnSruWfPBcr1LvOxL0r2sxsXVj13IepQPkMsNJFifsNPCipErk+F7YUz4iUFfbUSniGI8zVbXv8xTeoLAb0ux2eYXe6nLJPOz4TiYMbjsaRFKcYsIT+c7PnoLZnSY12p+lCJ6lrgsxX19FHunUw0IOoT5poYiVw0s2RfhGbHiFZLzHvHgoJx8HrHVAEM7w8+nN/OISkZBltbnAai4OHL62cHcXGm6TvdGPmOQYxhwHT0a0y0NJsStrsDDZCpyt2QQOCBHtmzEhRJMDFDU7Yqbhg/vBXrwB3BUfgysdnEmzQHU8nps8bvbxljQJVHwYpRceBKpbuS8vLwVNh4hIG5+pOaF4CBCNcit8ZopwYtMJ0E3eSiKv2To/z7ERm13YE0aJiDykpJSrwBLEjp9M7ZW9RwhDQzDThVnXugZ6LDF+3S1GN9pgHm5NCuT1IvoJMKXo2CNtJlBFsEAQEPOATydACVeqh++rjaZRvV54Lydxr00iU0rhybPWwcuD/4eoqJPH2qCB4cA2YJLFN7BNxc
  template:
    metadata:
      name: redis-secret
      namespace: sure
    type: Opaque
