apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml

helmCharts:
- name: alloy
  namespace: alloy
  releaseName: alloy
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 1.2.0
