apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./admin.approle.yaml
- ./application.yaml
- ./clusterpolicy.yaml
- ./editor.approle.yaml
- ./grafanaadmin-dennis.roleassignment.yaml
- ./grafanaadmin.approle.yaml
- ./password.yaml
- ./principal.yaml
- ./role.yaml
- ./rolebinding.yaml
- ./storeconfig.yaml
- ./viewer.approle.yaml
