apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: argocd
spec:
  rules:
  - name: generate-client-id-secret
    match:
      any:
      - resources:
          kinds:
          - applications.azuread.upbound.io/v1beta2/Application
          names:
          - argocd
    generate:
      generateExisting: true
      synchronize: true
      apiVersion: v1
      kind: Secret
      name: argocd-client-id
      namespace: argocd
      data:
        metadata:
          labels:
            app.kubernetes.io/part-of: argocd
        type: Opaque
        stringData:
          attribute.value: "{{ request.object.status.atProvider.clientId }}"
  - name: generate-rbac-cm
    match:
      any:
      - resources:
          kinds:
          - groups.azuread.upbound.io/v1beta2/Group
          names:
          - argocd-admins
    generate:
      generateExisting: true
      synchronize: true
      apiVersion: v1
      kind: ConfigMap
      name: argocd-rbac-cm
      namespace: argocd
      data:
        metadata:
          annotations:
            argocd.argoproj.io/tracking-id: argocd:/ConfigMap:argocd/argocd-rbac-cm
          labels:
            app.kubernetes.io/name: argocd-rbac-cm
            app.kubernetes.io/part-of: argocd
        data:
          policy.default: role:default
          policy.csv: |-
            g, {{ request.object.status.atProvider.objectId }}, role:admin
            p, role:default, *, *, */*, deny
            p, role:admin, *, *, */*, allow
          scopes: "[groups, email]"
