apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./admins-dennis.member.yaml
- ./admins.group.yaml
- ./application.yaml
- ./clusterpolicy.yaml
- ./password.yaml
- ./role.yaml
- ./rolebinding.yaml
- ./storeconfig.yaml
