apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:argocd-entra-reader
rules:
- apiGroups:
  - applications.azuread.upbound.io
  resources:
  - applications
  verbs:
  - list
  - get
- apiGroups:
  - groups.azuread.upbound.io
  resources:
  - groups
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:argocd-entra-reader
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno:argocd-entra-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno:argocd-secret-writer
  namespace: argocd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno:argocd-secret-writer
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
roleRef:
  kind: Role
  name: kyverno:argocd-secret-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno:argocd-configmap-writer
  namespace: argocd
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno:argocd-configmap-writer
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
roleRef:
  kind: Role
  name: kyverno:argocd-configmap-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno:argocd-secret-reader
  namespace: argocd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno:argocd-secret-reader
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: kyverno-admission-controller
  namespace: kyverno
roleRef:
  kind: Role
  name: kyverno:argocd-secret-reader
  apiGroup: rbac.authorization.k8s.io
