apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:argocd-secret-writer
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - create
  - update
  - delete
- apiGroups:
  - applications.azuread.upbound.io
  resources:
  - applications
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:argocd-secret-reader
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
