apiVersion: applications.azuread.upbound.io/v1beta2
kind: Application
metadata:
  name: immich
spec:
  forProvider:
    displayName: Axolotl Cloud - Immich
    requiredResourceAccess:
    - resourceAppId: 00000003-0000-0000-c000-000000000000 # Microsoft Graph
      resourceAccess:
      - id: e1fe6dd8-ba31-4d61-89e7-88639da4683d # User.Read
        type: Scope
    web:
      redirectUris:
      - https://photos.axolotl.cloud/api/oauth/mobile-redirect
      - https://photos.axolotl.cloud/user-settings
      - https://photos.axolotl.cloud/auth/login
      - https://photos.lan.axolotl.cloud/api/oauth/mobile-redirect
      - https://photos.lan.axolotl.cloud/user-settings
      - https://photos.lan.axolotl.cloud/auth/login
  providerConfigRef:
    name: default
