apiVersion: applications.azuread.upbound.io/v1beta1
kind: Password
metadata:
  name: immich
spec:
  forProvider:
    applicationObjectIdRef:
      name: immich
    displayName: Immich
    endDateRelative: 8766h # 1y
    rotateWhenChanged:
      lastChanged: "2026-07-19"
  publishConnectionDetailsTo:
    name: immich-oidc-secret
    configRef:
      name: immich-store-config
