apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./collab
- ./web
- ./worker
- ./backup.objectbucketclaim.yaml
- ./backup.objectstoreuser.yaml
- ./configmap.yaml
- ./imageupdater.yaml
- ./media.objectbucketclaim.yaml
- ./media.objectstoreuser.yaml
- ./namespace.yaml
- ./postgres.scheduledbackup.yaml
- ./postgres.yaml
- ./redis.externalsecret.yaml
- ./redis.sealedsecret.yaml
- ./redis.yaml
- ./s3.externalsecret.yaml
- ./sealedsecret.yaml
- ./secretstore.rbac.yaml
- ./secretstore.yaml

images:
- name: ghcr.io/yonder-sh/yonder
  digest: sha256:54bf6588bdec5901f18ecbe539be28c43dd2a955a36694bf42f60b507031edf0
  newTag: latest
- name: ghcr.io/yonder-sh/yonder-collab
  digest: sha256:d435e15b3d824f81fdd1a1b8870363e2fd7c8a0219ff0e17e046a4a407311647
  newTag: latest
