apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./collab
- ./web
- ./worker
- ./backup.objectbucketclaim.yaml
- ./backup.objectstoreuser.yaml
- ./configmap.yaml
- ./imageupdater.yaml
- ./media.objectbucketclaim.yaml
- ./media.objectstoreuser.yaml
- ./namespace.yaml
- ./postgres.scheduledbackup.yaml
- ./postgres.yaml
- ./redis.externalsecret.yaml
- ./redis.sealedsecret.yaml
- ./redis.yaml
- ./s3.externalsecret.yaml
- ./sealedsecret.yaml
- ./secretstore.rbac.yaml
- ./secretstore.yaml

images:
- name: ghcr.io/yonder-sh/yonder
  digest: sha256:2627ef9857f6d760ceb92562b535c44ea026ee4c4476869be2f99941998df989
  newTag: latest
- name: ghcr.io/yonder-sh/yonder-collab
  digest: sha256:315cfa5b02d1f3e024b00748399506859dde036d86776988ec977f78fe836813
  newTag: latest
