apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./collab
- ./web
- ./worker
- ./backup.objectbucketclaim.yaml
- ./backup.objectstoreuser.yaml
- ./configmap.yaml
- ./imageupdater.yaml
- ./media.objectbucketclaim.yaml
- ./media.objectstoreuser.yaml
- ./namespace.yaml
- ./postgres.scheduledbackup.yaml
- ./postgres.yaml
- ./redis.externalsecret.yaml
- ./redis.sealedsecret.yaml
- ./redis.yaml
- ./s3.externalsecret.yaml
- ./sealedsecret.yaml
- ./secretstore.rbac.yaml
- ./secretstore.yaml

images:
- name: ghcr.io/yonder-sh/yonder
  digest: sha256:018e3b7dd9e467d9cdb28a0c158cd7d9521496e4908031e50239f140b4fbdae9
  newTag: latest
- name: ghcr.io/yonder-sh/yonder-collab
  digest: sha256:7ad1625a31032f201b2b1be9dba179a5835c72f3f668d46ffb51a144ec46405c
  newTag: latest
