apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yonder-redis-secret
  namespace: yonder
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: yonder-redis-secret
    template:
      data:
        REDIS_URL: "redis://:{{ .password }}@redis.yonder.svc.cluster.local:6379/0"
  data:
  - secretKey: password
    remoteRef:
      key: redis-secret
      property: password
