apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: yonder
spec:
  encryptedData:
    password: AgAn/CLcCLmSoEDkC/TnhMRLQushUgPE3pAJPHiwAUyYQSigEsREnE08l+Cp854nLBXRI1PlmruAc1u3njNZe3oDTdDYCi0ADAiD/JC/bR19atFig4sj0ICfveqR9qwoD/LkSMwqnCkRplUPxno9JxhuuOY+m0c/++Lmcpc3HHCjGEWolFusuEwarOZL4guvU6KtbEsAwVHqCdclw1LeRpzWcU/6WxGoB16/i8xVJPewwuKah9NP1UsBeI+B+R043LRnc9MqvhbB1DCVm7rDLWp/j9rNCjJ4XEkruRgkKhWWlaxPHE+fAxyu2NkahL5FBcKWY8Ej4sGGKLwTO30IZHij81Yo/LrGRwQDKowvjfa4atKJf7/PR8swKucgshYhQcfQmDs2BbcuY9OUBRvEvWSNKi6yg5M5OJXJ7aJrfOo4P1DEkL75U4qrNb5mbSX6V7XgMpf72nQ3aYnD590EYh7tpGmLp+9thWl/liulR4x+4iFlB1wYx+NVA81l3iSj1hU6bHRyBWpRsvtU3Rq2jQhP3i7pFyddduQw5gWJEgMT1wP/37Epbq6xHkJrIBkJXE4oNV1KTHlFiBcWySWVQaz2RfTfrdxvYSm5IF03YIE00S2hqY172W7W6RfMOktNi6+BE0bpBBRKSLQwxxnA1fOv6BHZ0ARwzLygizUW7c7o/FZK8/+cO5VXSwYzGpDOmOMRp45I8tCLrlFo0v/Ny0iO/gQodAbFXSKX+NO/WKP5OQ==
  template:
    metadata:
      name: redis-secret
      namespace: yonder
    type: Opaque
