apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yonder-s3-secret
  namespace: yonder
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: yonder-s3-secret
    template:
      data:
        S3_ACCESS_KEY_ID: "{{ .accessKey }}"
        S3_SECRET_ACCESS_KEY: "{{ .secretKey }}"
  data:
  - secretKey: accessKey
    remoteRef:
      key: rook-ceph-object-user-axolotl-object-store-yonder-media
      property: AccessKey
  - secretKey: secretKey
    remoteRef:
      key: rook-ceph-object-user-axolotl-object-store-yonder-media
      property: SecretKey
