apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ./entra
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.12/manifests/ha/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.16.0/manifests/install.yaml
- ./apps.appproject.yaml
- ./axolotl-cluster.secret.yaml
- ./core.appproject.yaml
- ./httproute.yaml
- ./infrastructure-repo.sealedsecret.yaml
- ./namespace.yaml
- ./root.appproject.yaml
- ./service.yaml

patchesStrategicMerge:
- ./configmap.yaml

patches:
- target:
    kind: NetworkPolicy
    name: argocd-application-controller-network-policy
  path: networkpolicyi1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-applicationset-controller-network-policy
  path: networkpolicyi1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-dex-server-network-policy
  path: networkpolicyi2.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-notifications-controller-network-policy
  path: networkpolicyi1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-redis-ha-proxy-network-policy
  path: networkpolicyi1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-redis-ha-server-network-policy
  path: networkpolicyi1e1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-repo-server-network-policy
  path: networkpolicyi2.patch.yaml
