apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ./entra
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.12/manifests/ha/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.16.0/manifests/install.yaml
- ./apps.appproject.yaml
- ./axolotl-cluster.secret.yaml
- ./core.appproject.yaml
- ./httproute.yaml
- ./image-updater.service.yaml
- ./infrastructure-repo.sealedsecret.yaml
- ./namespace.yaml
- ./root.appproject.yaml

patchesStrategicMerge:
- ./configmap.yaml

patches:
- target:
    kind: NetworkPolicy
    name: argocd-application-controller-network-policy
  path: ../../../common/networkpolicy/networkpolicyi1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-applicationset-controller-network-policy
  path: ../../../common/networkpolicy/networkpolicyi1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-dex-server-network-policy
  path: ../../../common/networkpolicy/networkpolicyi2.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-notifications-controller-network-policy
  path: ../../../common/networkpolicy/networkpolicyi1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-redis-ha-proxy-network-policy
  path: ../../../common/networkpolicy/networkpolicyi1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-redis-ha-server-network-policy
  path: ../../../common/networkpolicy/networkpolicyi1e1.patch.yaml
- target:
    kind: NetworkPolicy
    name: argocd-repo-server-network-policy
  path: ../../../common/networkpolicy/networkpolicyi2.patch.yaml
- target:
    version: v1
    kind: Deployment
    name: argocd-image-updater
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/ports/0
      value:
        name: app
        containerPort: 8080
    - op: add
      path: /spec/template/spec/containers/0/ports/-
      value:
        name: metrics
        containerPort: 8082
- target:
    version: v1
    kind: Service
    name: argocd-applicationset-controller
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
- target:
    version: v1
    kind: Service
    name: argocd-dex-server
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5558"
- target:
    version: v1
    kind: Service
    name: argocd-metrics
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
- target:
    version: v1
    kind: Service
    name: argocd-notifications-controller-metrics
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
- target:
    version: v1
    kind: Service
    name: argocd-repo-server
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
- target:
    version: v1
    kind: Service
    name: argocd-server-metrics
  patch: |
    - op: add
      path: /metadata/annotations
      value:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
