apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ./entra
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.12/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.16.0/manifests/install.yaml
- ./apps.appproject.yaml
- ./axolotl-cluster.secret.yaml
- ./core.appproject.yaml
- ./httproute.yaml
- ./infrastructure-repo.sealedsecret.yaml
- ./namespace.yaml
- ./rbac.configmap.yaml
- ./root.appproject.yaml
- ./service.yaml

patchesStrategicMerge:
- ./configmap.yaml
