apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac
  namespace: argocd
data:
  policy.default: role:default
  policy.csv: |
    p, role:default, *, *, */*, deny
    p, role:admin, *, *, */*, allow
  scopes: "[groups, email]"
