apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stats-config
  namespace: istio-ingress
spec:
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        stats_config:
          stats_tags:
          - tag_name: phase
            regex: "(_phase=([a-z_]+))"
          - tag_name: rule_id
            regex: "(_ruleid=([0-9]+))"
          - tag_name: identifier
            regex: "(_identifier=([0-9a-z.:]+))"
          - tag_name: owner
            regex: "(_owner=([0-9a-z.:]+))"
          - tag_name: authority
            regex: "(_authority=([0-9a-z.:]+))"
          use_all_default_tags: true
