apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: axolotl-waf
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: axolotl
  url: oci://ghcr.io/corazawaf/coraza-proxy-wasm:0.6.0
  imagePullPolicy: IfNotPresent
  phase: AUTHN
  pluginConfig:
    default_directives: default
    directives_map:
      default:
      - Include @recommended-conf
      # - SecRuleEngine On
      - SecAuditEngine RelevantOnly
      - Include @crs-setup-conf
      # False positive: allow application/octet-stream, remove null byte check (920270), and remove CR/LF check (921150) for Hubble's gRPC endpoints
      - SecRule REQUEST_URI "@rx ^/api/(control-stream|service-map-stream)$" "id:1000002,phase:1,pass,nolog,setvar:'tx.allowed_request_content_type=|application/octet-stream|',ctl:ruleRemoveById=920270,ctl:ruleRemoveById=921150"
      - Include @owasp_crs/*.conf
      # False positive: allow mTLS client certificate from Cloudflare
      - SecRuleUpdateTargetById 921140 "!REQUEST_HEADERS:x-forwarded-client-cert"
    metrics_labels:
      gateway: axolotl
