apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sure
spec:
  rules:
  - name: generate-oidc-config
    match:
      any:
      - resources:
          kinds:
          - serviceprincipals.azuread.upbound.io/v1beta2/Principal
          names:
          - sure
    generate:
      generateExisting: true
      synchronize: true
      apiVersion: v1
      kind: ConfigMap
      name: sure-oidc-config
      namespace: sure
      data:
        data:
          OIDC_CLIENT_ID: "{{ request.object.status.atProvider.applicationId }}"
          OIDC_ISSUER: https://login.microsoftonline.com/{{ request.object.status.atProvider.applicationTenantId }}/v2.0
