apiVersion: applications.azuread.upbound.io/v1beta1
kind: Password
metadata:
  name: sure
spec:
  forProvider:
    applicationObjectIdRef:
      name: sure
    displayName: Sure
    endDateRelative: 8766h # 1y
    rotateWhenChanged:
      lastChanged: "2026-07-14"
  publishConnectionDetailsTo:
    name: sure-oidc-secret
    configRef:
      name: sure-store-config
