apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./httproute.yaml
- ./namespace.yaml
- ./objectbucketclaim.yaml
- ./objectstoreuser.yaml
- ./service.yaml
images:
- name: ghcr.io/den4200/dennispham.me
  digest: sha256:dec01ed2ad7616b55789621927178271e78b1e2686bd736293997ef6fc9b43ac
