apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./httproute.yaml
- ./namespace.yaml
- ./objectbucketclaim.yaml
- ./objectstoreuser.yaml
- ./service.yaml
images:
- name: ghcr.io/den4200/dennispham.me
  digest: sha256:981c2ca49554f548570cacf435fd1a9f80d587de91bf1a5ecab7a286fb3dc771
