apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./httproute.yaml
- ./namespace.yaml
- ./objectbucketclaim.yaml
- ./objectstoreuser.yaml
- ./service.yaml
images:
- name: ghcr.io/den4200/dennispham.me
  digest: sha256:27f58161dbe7599e97e950bc006980f984463dbe2884f0089a28239c68588867
